spring.application.name=taskhub
server.port=9090
spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=Taskhub;encrypt=false;trustServerCertificate=true
spring.datasource.username=webtaskhub
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

